name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"
  push:
    branches:
      - "main"

jobs:
  markgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: trinhminhtriet/readme-markgen-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - uses: trinhminhtriet/readme-markgen-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "README_ZH.md.tpl"
          writeTo: "README_ZH.md"

      - name: Commit changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update generated README" && git push)
